/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/root'
import { Route as authLayoutImport } from './routes/auth/layout'
import { Route as indexImport } from './routes/index'
import { Route as authSignUpImport } from './routes/auth/sign-up'
import { Route as authSignInImport } from './routes/auth/sign-in'

// Create/Update Routes

const authLayoutRoute = authLayoutImport.update({
  id: '/_auth-layout-id',
  getParentRoute: () => rootRoute,
} as any)

const indexRoute = indexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const authSignUpRoute = authSignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authLayoutRoute,
} as any)

const authSignInRoute = authSignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexImport
      parentRoute: typeof rootRoute
    }
    '/_auth-layout-id': {
      id: '/_auth-layout-id'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_auth-layout-id/sign-in': {
      id: '/_auth-layout-id/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInImport
      parentRoute: typeof authLayoutImport
    }
    '/_auth-layout-id/sign-up': {
      id: '/_auth-layout-id/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpImport
      parentRoute: typeof authLayoutImport
    }
  }
}

// Create and export the route tree

interface authLayoutRouteChildren {
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof indexRoute
  '': typeof authLayoutRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
}

export interface FileRoutesByTo {
  '/': typeof indexRoute
  '': typeof authLayoutRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof indexRoute
  '/_auth-layout-id': typeof authLayoutRouteWithChildren
  '/_auth-layout-id/sign-in': typeof authSignInRoute
  '/_auth-layout-id/sign-up': typeof authSignUpRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/sign-in' | '/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/sign-in' | '/sign-up'
  id:
    | '__root__'
    | '/'
    | '/_auth-layout-id'
    | '/_auth-layout-id/sign-in'
    | '/_auth-layout-id/sign-up'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  indexRoute: typeof indexRoute
  authLayoutRoute: typeof authLayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  authLayoutRoute: authLayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "root.tsx",
      "children": [
        "/",
        "/_auth-layout-id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth-layout-id": {
      "filePath": "auth/layout.tsx",
      "children": [
        "/_auth-layout-id/sign-in",
        "/_auth-layout-id/sign-up"
      ]
    },
    "/_auth-layout-id/sign-in": {
      "filePath": "auth/sign-in.tsx",
      "parent": "/_auth-layout-id"
    },
    "/_auth-layout-id/sign-up": {
      "filePath": "auth/sign-up.tsx",
      "parent": "/_auth-layout-id"
    }
  }
}
ROUTE_MANIFEST_END */
