/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/root'
import { Route as artistCreateImport } from './routes/artist/create'
import { Route as layoutImport } from './routes/layout'
import { Route as artistLayoutImport } from './routes/artist/layout'
import { Route as authLayoutImport } from './routes/auth/layout'
import { Route as authSignUpImport } from './routes/auth/sign-up'
import { Route as authSignInImport } from './routes/auth/sign-in'
import { Route as indexImport } from './routes/index'
import { Route as artistOverviewImport } from './routes/artist/overview'
import { Route as artistArtworkImport } from './routes/artist/artwork'

// Create/Update Routes

const artistCreateRoute = artistCreateImport.update({
  id: '/create-artist',
  path: '/create-artist',
  getParentRoute: () => rootRoute,
} as any)

const layoutRoute = layoutImport.update({
  id: '/_main-layout-id',
  getParentRoute: () => rootRoute,
} as any)

const artistLayoutRoute = artistLayoutImport.update({
  id: '/_dashboard-layout-id',
  getParentRoute: () => rootRoute,
} as any)

const authLayoutRoute = authLayoutImport.update({
  id: '/_auth-layout-id',
  getParentRoute: () => rootRoute,
} as any)

const authSignUpRoute = authSignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authLayoutRoute,
} as any)

const authSignInRoute = authSignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authLayoutRoute,
} as any)

const indexRoute = indexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => layoutRoute,
} as any)

const artistOverviewRoute = artistOverviewImport.update({
  id: '/dashboard/overview',
  path: '/dashboard/overview',
  getParentRoute: () => artistLayoutRoute,
} as any)

const artistArtworkRoute = artistArtworkImport.update({
  id: '/dashboard/artworks',
  path: '/dashboard/artworks',
  getParentRoute: () => artistLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth-layout-id': {
      id: '/_auth-layout-id'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard-layout-id': {
      id: '/_dashboard-layout-id'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof artistLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_main-layout-id': {
      id: '/_main-layout-id'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof layoutImport
      parentRoute: typeof rootRoute
    }
    '/create-artist': {
      id: '/create-artist'
      path: '/create-artist'
      fullPath: '/create-artist'
      preLoaderRoute: typeof artistCreateImport
      parentRoute: typeof rootRoute
    }
    '/_main-layout-id/': {
      id: '/_main-layout-id/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexImport
      parentRoute: typeof layoutImport
    }
    '/_auth-layout-id/sign-in': {
      id: '/_auth-layout-id/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInImport
      parentRoute: typeof authLayoutImport
    }
    '/_auth-layout-id/sign-up': {
      id: '/_auth-layout-id/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpImport
      parentRoute: typeof authLayoutImport
    }
    '/_dashboard-layout-id/dashboard/artworks': {
      id: '/_dashboard-layout-id/dashboard/artworks'
      path: '/dashboard/artworks'
      fullPath: '/dashboard/artworks'
      preLoaderRoute: typeof artistArtworkImport
      parentRoute: typeof artistLayoutImport
    }
    '/_dashboard-layout-id/dashboard/overview': {
      id: '/_dashboard-layout-id/dashboard/overview'
      path: '/dashboard/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof artistOverviewImport
      parentRoute: typeof artistLayoutImport
    }
  }
}

// Create and export the route tree

interface authLayoutRouteChildren {
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface artistLayoutRouteChildren {
  artistArtworkRoute: typeof artistArtworkRoute
  artistOverviewRoute: typeof artistOverviewRoute
}

const artistLayoutRouteChildren: artistLayoutRouteChildren = {
  artistArtworkRoute: artistArtworkRoute,
  artistOverviewRoute: artistOverviewRoute,
}

const artistLayoutRouteWithChildren = artistLayoutRoute._addFileChildren(
  artistLayoutRouteChildren,
)

interface layoutRouteChildren {
  indexRoute: typeof indexRoute
}

const layoutRouteChildren: layoutRouteChildren = {
  indexRoute: indexRoute,
}

const layoutRouteWithChildren =
  layoutRoute._addFileChildren(layoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof layoutRouteWithChildren
  '/create-artist': typeof artistCreateRoute
  '/': typeof indexRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/dashboard/artworks': typeof artistArtworkRoute
  '/dashboard/overview': typeof artistOverviewRoute
}

export interface FileRoutesByTo {
  '': typeof artistLayoutRouteWithChildren
  '/create-artist': typeof artistCreateRoute
  '/': typeof indexRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/dashboard/artworks': typeof artistArtworkRoute
  '/dashboard/overview': typeof artistOverviewRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth-layout-id': typeof authLayoutRouteWithChildren
  '/_dashboard-layout-id': typeof artistLayoutRouteWithChildren
  '/_main-layout-id': typeof layoutRouteWithChildren
  '/create-artist': typeof artistCreateRoute
  '/_main-layout-id/': typeof indexRoute
  '/_auth-layout-id/sign-in': typeof authSignInRoute
  '/_auth-layout-id/sign-up': typeof authSignUpRoute
  '/_dashboard-layout-id/dashboard/artworks': typeof artistArtworkRoute
  '/_dashboard-layout-id/dashboard/overview': typeof artistOverviewRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/create-artist'
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/artworks'
    | '/dashboard/overview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/create-artist'
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/artworks'
    | '/dashboard/overview'
  id:
    | '__root__'
    | '/_auth-layout-id'
    | '/_dashboard-layout-id'
    | '/_main-layout-id'
    | '/create-artist'
    | '/_main-layout-id/'
    | '/_auth-layout-id/sign-in'
    | '/_auth-layout-id/sign-up'
    | '/_dashboard-layout-id/dashboard/artworks'
    | '/_dashboard-layout-id/dashboard/overview'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  authLayoutRoute: typeof authLayoutRouteWithChildren
  artistLayoutRoute: typeof artistLayoutRouteWithChildren
  layoutRoute: typeof layoutRouteWithChildren
  artistCreateRoute: typeof artistCreateRoute
}

const rootRouteChildren: RootRouteChildren = {
  authLayoutRoute: authLayoutRouteWithChildren,
  artistLayoutRoute: artistLayoutRouteWithChildren,
  layoutRoute: layoutRouteWithChildren,
  artistCreateRoute: artistCreateRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "root.tsx",
      "children": [
        "/_auth-layout-id",
        "/_dashboard-layout-id",
        "/_main-layout-id",
        "/create-artist"
      ]
    },
    "/_auth-layout-id": {
      "filePath": "auth/layout.tsx",
      "children": [
        "/_auth-layout-id/sign-in",
        "/_auth-layout-id/sign-up"
      ]
    },
    "/_dashboard-layout-id": {
      "filePath": "artist/layout.tsx",
      "children": [
        "/_dashboard-layout-id/dashboard/artworks",
        "/_dashboard-layout-id/dashboard/overview"
      ]
    },
    "/_main-layout-id": {
      "filePath": "layout.tsx",
      "children": [
        "/_main-layout-id/"
      ]
    },
    "/create-artist": {
      "filePath": "artist/create.tsx"
    },
    "/_main-layout-id/": {
      "filePath": "index.tsx",
      "parent": "/_main-layout-id"
    },
    "/_auth-layout-id/sign-in": {
      "filePath": "auth/sign-in.tsx",
      "parent": "/_auth-layout-id"
    },
    "/_auth-layout-id/sign-up": {
      "filePath": "auth/sign-up.tsx",
      "parent": "/_auth-layout-id"
    },
    "/_dashboard-layout-id/dashboard/artworks": {
      "filePath": "artist/artwork.tsx",
      "parent": "/_dashboard-layout-id"
    },
    "/_dashboard-layout-id/dashboard/overview": {
      "filePath": "artist/overview.tsx",
      "parent": "/_dashboard-layout-id"
    }
  }
}
ROUTE_MANIFEST_END */
